project_name: pgroll

before:
  hooks:
    - go mod tidy

builds:
  - id: build_noncgo
    binary: pgroll
    ldflags:
      - -X github.com/xataio/pgroll/cmd.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

# brews:
#   -
#     name: mediumautopost
#     homepage: "https://www.xata.io"
#     description: "Postgres zero-downtime migrations made easy"
#     tap:
#       owner: xataio
#       name: homebrew-pgroll

archives:
  - format: binary
    # pgroll.win.amd64
    name_template: >-
      {{ .ProjectName }}.{{ if eq .Os "windows" }}win{{ else if eq .Os "darwin" }}macos{{ else }}{{ .Os }}{{ end }}.{{ .Arch }}
    files:
      - LICENSE*

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
